### ISSUE TITLE
can't use nvim because of .private submodules

### ISSUE THREAD

**Issue by Toni500github** [AlexvZyl/.dotfiles#14]
just copied the nvim dir to `~/.config` then removed `~/.local/share/nvim` and `~/.cache/nvim` for then installing packer. when i started nvim, it gave some errors like `Error while calling lua chunk: /home/toni/.config/nvim/lua/alex/init.lua:4: Vim(luafile):E5112: Error while creating lua chunk: cannot open /home/toni/.private/nvim_env.lua: No such file or directory` 

this is caused because it needed a file that was on the .private submodules but it's literally private and nobody else can clone it
maybe add the file on this repo?

**Comment by AlexvZyl** [comment]
That file contains private keys, which I cannot share publicly.  It is an easy fix though, let me quickly do that.

**Comment by Toni500github** [comment]
oh alright, already fixed it by commeting the line. but now i get a bunch of errors each time i start nvim then disappear. idk why

**Comment by AlexvZyl** [comment]
Ah, are those errors related to the ChatGPT plugin?

**Comment by Toni500github** [comment]
they disappears too fast that i can't even read them, plus when i type some commands like `:q` `:wq`  noice.nvim says some error like `/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim`

**Comment by Toni500github** [comment]
> Ah, are those errors related to the ChatGPT plugin?

oh i managed to take the screenshot 
![image](https://user-images.githubusercontent.com/88878648/234620909-1dfba22f-27c3-4cbb-9b6a-2b6b64b90597.png)

**Comment by AlexvZyl** [comment]
You can run the command `:messages` to show your message history.

**Comment by AlexvZyl** [comment]
You can please show me the output of `nvim -v`?

**Comment by Toni500github** [comment]
> You can please show me the output of `nvim -v`? Run it in your terminal.

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilato da runner@fv-az178-366

Features: +acl +iconv +tui
See ":help feature-compile"

   file vimrc di sistema: "$VIM/sysinit.vim"
         $VIM di riserva: "/share/nvim"

Run :checkhealth for more info

**Comment by Toni500github** [comment]
sorry if some info are written in italian

**Comment by AlexvZyl** [comment]
No worries.  Your Neovim version is outdated, that version cannot configure the `statuscolumn`.  I will make it check the Neovim version before trying to set the statuscolumn.

Though, I would suggest you update the version.  Are you on Debian?

**Comment by AlexvZyl** [comment]
It was added in 0.9 https://github.com/neovim/neovim/pull/20621.

**Comment by Toni500github** [comment]
> Though, I would suggest you update the version. Are you on Debian?

no, i'm on linux mint 20.3 which is based on Ubuntu 20.04 focal

**Comment by Toni500github** [comment]
> And Ubuntu is based on Debian. You should get the Neovim version that supports the statuscolumn in the next few months.

maybe i'll just compile from source or download the release version

**Comment by AlexvZyl** [comment]
Do you have any other erroes when starting Neovim?

**Comment by Toni500github** [comment]
> they disappears too fast that i can't even read them, plus when i type some commands like `:q` `:wq` noice.nvim says some error like `/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim`

this one

**Comment by AlexvZyl** [comment]
Hmm.  Try `TSUpdate` or 'TSUpdateSync', I can't remember which one it is.

**Comment by AlexvZyl** [comment]
Otherwise check here https://github.com/folke/noice.nvim/issues/260/

**Comment by AlexvZyl** [comment]
Yes, so the ChatGPT plugin requires an OPEN AI key (the ones I have hosted in my private repo).  So either you get your own key and set it up, or you remove the plugin.

**Comment by AlexvZyl** [comment]
Should be able to run Neovim now without setting it up.

**Comment by Toni500github** [comment]
alright everything it's fine now. thank you!

**Comment by AlexvZyl** [comment]
No worries! Glad I could fix some things.
