### ISSUE TITLE
How did you make btop++ look like in the photos?

### ISSUE THREAD

**Issue by femto-code** [AlexvZyl/.dotfiles#15]

**Comment by AlexvZyl** [comment]
In the photo it is using the terminal theme.  Also using rounded corners.

![image](https://github.com/AlexvZyl/.dotfiles/assets/81622310/3ff9f969-7688-4fc3-b2f3-4e0e7e51156e)

**Comment by AlexvZyl** [comment]
Also, the edges of my terminal are padded.

**Comment by AlexvZyl** [comment]
[Nordic](https://github.com/AlexvZyl/nordic.nvim/blob/main/extras/kitty/nordic.conf) :)

**Comment by femto-code** [comment]
Cool, thanks! Did you change anything about the font rendering? The terminal font does not seem to be bold at times where it does for me with the same settings and font. Did you turn off the bold style?

**Comment by AlexvZyl** [comment]
No, I definitely have bold fonts enabled.  It could just be the font I am using. 

Also, in the screenshots in the README I am using medium as my normal font, which makes bold text harder to spot I guess.  I am no longer using medium, though.
