### ISSUE TITLE
Wallpaper Recommendations

### ISSUE THREAD

**Issue by AlexvZyl** [AlexvZyl/.dotfiles#3]
If you have a wallpaper that works nicely with this setup, please post it here!

**Comment by AlexvZyl** [comment]
![National_Park_Nord](https://user-images.githubusercontent.com/81622310/211795222-6b12b9a4-2d88-467a-a254-d621d9c09470.png)

![Rocket_Nord](https://user-images.githubusercontent.com/81622310/211795485-826464f1-7283-43e7-b401-0caf773bbd5d.png)

![Kurs_Space_Nord](https://user-images.githubusercontent.com/81622310/211795322-bdd54585-bc2c-4a03-9f1c-b17ac742550a.png)

**Comment by AlexvZyl** [comment]
![Mando_Grogu_Nord](https://user-images.githubusercontent.com/81622310/211795663-c0539769-bc9b-4bf6-adbe-6e29711e3576.png)

**Comment by AlexvZyl** [comment]
![Cloud_1_Nord](https://user-images.githubusercontent.com/81622310/234625283-7f600d91-e29c-482d-ba66-b95cfcd6f772.png)

![Cloud_2_Nord](https://user-images.githubusercontent.com/81622310/234625211-2c5a7ab7-8ea5-4e1a-b1a4-a2c37bc9558f.png)

**Comment by a-mesin** [comment]
This repo has some fitting wallpapers: https://github.com/linuxdotexe/nordic-wallpapers
